# Generated by Django 4.1.2 on 2022-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_of_projects',
            field=models.CharField(choices=[('Web', 'Web'), ('Python', 'Python')], default='Web', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
