# Generated by Django 4.1.2 on 2022-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
