# Generated by Django 4.1.2 on 2022-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_project_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="{% static 'images/default.svg' %}", upload_to=""
            ),
        ),
    ]
