# Generated by Django 4.1.2 on 2022-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="static/main/images/default.png",
                upload_to="static/main/images/",
            ),
        ),
    ]
