# Generated by Django 4.1.2 on 2022-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="image_name",
            field=models.CharField(default="default.svg", max_length=100),
        ),
    ]
